using System.Collections.Generic;

namespace DistanceScraper
{
	public class OfficialLeaderboards
	{
		public static List<string> SprintLevelNames = new List<string>()
		{
			"Chroma",
			"Vector Valley",
			"Static Fire Signal",
			"Shallow",
			"Incline",
			"Station",
			"Particular Journey",
			"Turbines",
			"COAT Speedway",
			"Tharsis Tholus",
			"Virtual Rift",
			"Sea",
			"Beta Echoes",
			"Sender",
			"Fiber",
			"The Manor",
			"Uncanny Valley",
			"Le Teleputo",
			"Method",
			"Binary Construct",
			"Amusement",
			"Outrun",
			"Iris",
			"Volcanic Rush",
			"Ruin",
			"Moonlight",
			"Instability",
			"Shafty",
			"Precept",
			"Overdrive",
			"Past",
			"Neo Seoul",
			"Event Horizon",
			"Yellow",
			"Sugar Rush",
			"Sword",
			"Forsaken Shrine",
			"Noir",
			"Brink",
			"Projection",
			"Vibe",
			"Luminescence",
			"Paradise Lost",
			"Epicentre",
			"Neo Seoul II",
			"Serenity",
			"Red",
			"Knowledge",
			"White",
			"Tetreal",
			"Mentality",
			"Wired",
			"Hardline",
			"Gravity",
			"Digital",
			"Monument",
			"Fulcrum",
			"SR Motorplex",
			"Hard Light Transfer",
			"Impulse",
			"Observatory",
			"Eclipse",
			"Shrine",
			"Liminal",
			"White Lightning Returns",
			"Affect",
			"The Night Before",
			"Industrial Fury",
			"Fallback Protocol",
			"Cosmic Glitch",
			"Zenith",
			"Candles of Hekate",
			"Sector 0",
			"Micro",
			"Inferno",
			"Cataclysm",
			"Diversion",
			"Euphoria",
			"Entanglement",
			"Automation",
			"Abyss",
			"Embers",
			"Isolation",
			"Repulsion",
			"Compression",
			"Research",
			"Contagion",
			"Overload",
			"Ascension",
			"Forgotten Utopia",
			"A Deeper Void",
			"Eye of the Storm",
			"The Sentinel Still Watches",
			"Shadow of the Beast",
			"Pulse of a Violent Heart",
			"It Was Supposed To Be Perfect",
			"Resonance",
			"Deterrence",
			"Terminus",
			"Broken Symmetry",
			"Lost Society",
			"Negative Space",
			"Departure",
			"Ground Zero",
			"The Observer Effect",
			"Aftermath",
			"Friction",
			"The Thing About Machines",
			"Corruption",
			"Dissolution",
			"Falling Through",
			"Monolith",
			"Destination Unknown",
			"Rooftops",
			"Factory",
			"Stronghold",
			"Approach",
			"Continuum",
			"Escape",
		};
	}
}
