using System.Collections.Generic;

namespace DistanceScraper
{
	public class OfficialLeaderboards
	{
		public static readonly List<Leaderboard> SprintLevels = new()
		{
			new Leaderboard("Chroma", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Vector Valley", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Static Fire Signal", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Shallow", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Incline", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Station", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Whisper", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Particular Journey", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Turbines", LevelType.Sprint, "Ignition", true),
			new Leaderboard("COAT Speedway", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Tharsis Tholus", LevelType.Sprint, "Ignition", true),
			new Leaderboard("Virtual Rift", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Sea", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Beta Echoes", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Sender", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Absorption", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Fiber", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Homestead", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Salmon", LevelType.Sprint, "High Impact", true),
			new Leaderboard("The Manor", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Uncanny Valley", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Sakura Skyway", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Le Teleputo", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Method", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Binary Construct", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Storm 2: Neon Thunder", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Amusement", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Outrun", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Iris", LevelType.Sprint, "High Impact", true),
			new Leaderboard("Volcanic Rush", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Ruin", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Moonlight", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Instability", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Shafty", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Precept", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Aeris", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Overdrive", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Floral", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Past", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Neo Seoul", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Event Horizon", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Yellow", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Sugar Rush", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Sword", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Forsaken Shrine", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Toy Time", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Noir", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Brink", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Projection", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Vibe", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Luminescence", LevelType.Sprint, "Brute Force", true),
			new Leaderboard("Paradise Lost", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Epicentre", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Neo Seoul II", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Serenity", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Red", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Table", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Knowledge", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Pacebreaker", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("White", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Tetreal", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Mentality", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Wired", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Hardline", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Gravity", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Digital", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Monument", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Fulcrum", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("SR Motorplex", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Hard Light Transfer", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Impulse", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Observatory", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Earth", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Eclipse", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Shrine", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Liminal", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("White Lightning Returns", LevelType.Sprint, "Overdrive", true),
			new Leaderboard("Affect", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("The Night Before", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Industrial Fury", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Fallback Protocol", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Cosmic Glitch", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Orthodox", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Zenith", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Micro", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Candles of Hekate", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Sector 0", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Macro", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Glide in the Hole", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Inferno", LevelType.Sprint, "Nightmare Fuel", true),
			new Leaderboard("Cataclysm", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Diversion", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Euphoria", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Entanglement", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Automation", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Abyss", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Embers", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Isolation", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Repulsion", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Compression", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Research", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Contagion", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Overload", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Ascension", LevelType.Sprint, "Adventure", true),
			new Leaderboard("Forgotten Utopia", LevelType.Sprint, "Lost to Echoes", true),
			new Leaderboard("A Deeper Void", LevelType.Sprint, "Lost to Echoes", true),
			new Leaderboard("Eye of the Storm", LevelType.Sprint, "Lost to Echoes", true),
			new Leaderboard("The Sentinel Still Watches", LevelType.Sprint, "Lost to Echoes", true),
			new Leaderboard("Shadow of the Beast", LevelType.Sprint, "Lost to Echoes", true),
			new Leaderboard("Pulse of a Violent Heart", LevelType.Sprint, "Lost to Echoes", true),
			new Leaderboard("It Was Supposed To Be Perfect", LevelType.Sprint, "Lost to Echoes", true),
			new Leaderboard("Resonance", LevelType.Sprint, "Nexus", true),
			new Leaderboard("Deterrence", LevelType.Sprint, "Nexus", true),
			new Leaderboard("Terminus", LevelType.Sprint, "Nexus", true),
			new Leaderboard("Broken Symmetry", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Lost Society", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Negative Space", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Departure", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Ground Zero", LevelType.Sprint, "Legacy", true),
			new Leaderboard("The Observer Effect", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Aftermath", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Friction", LevelType.Sprint, "Legacy", true),
			new Leaderboard("The Thing About Machines", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Corruption", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Dissolution", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Falling Through", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Monolith", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Destination Unknown", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Rooftops", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Factory", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Stronghold", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Approach", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Continuum", LevelType.Sprint, "Legacy", true),
			new Leaderboard("Escape", LevelType.Sprint, "Legacy", true),
		};

		public static readonly List<Leaderboard> ChallengeLevels = new()
		{
			new Leaderboard("Detached", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("44 Second Theory", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Transfer", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Divide", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Thunder Struck", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Electric", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Descent", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Disassembly Line", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Red Heat", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Grinder", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Dodge", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Elevation", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Obsidian", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Hexahorrific", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Too Many Dots", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Variant Blue", LevelType.Challenge, "White Knuckle", true),
			new Leaderboard("Biotec 4", LevelType.Challenge, "White Knuckle", true),
		};
	}
}
